### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by worming004** [gleam-lang/otp#43]
Hello,

The readme refer to a blog post for gleam 0.12, explaining processes and channels.

Could we update the blog post (and i'll open an issue on gleam/website to mark this blog post as outdated) ?
Or can we update the current readme to show basic examples ?

I'll be happy to send a PR after few guidances of what solution is the best from your opinion

**Comment by lpil** [comment]
Good idea! Let's add a note to that post saying it was for a previous version, and a bunch of examples in the README would be good.

**Comment by tankorsmash** [comment]
I'm not sure if this is the right issue to mention this, but as a newbie the actor's docs are missing an import (or an explanation) for what `Subject` is. It seems like the fix is importing `import gleam/erlang/process.{type Subject}`. 

https://github.com/gleam-lang/otp/blob/946a0e969ecc88fcd1ea77becf5a09c36eef1970/src/gleam/otp/actor.gleam#L81

**Comment by lpil** [comment]
Thank you.
